import 'package:flutter/material.dart';
import 'package:interna/features/home/data/internship_model.dart';

/// Test fixtures used strictly inside the test suite.
final List<InternshipOpportunity> testInternships = [
  const InternshipOpportunity(
    id: 'chipmong-01',
    role: 'Mobile App Developer Intern',
    company: 'Chip Mong',
    category: 'Tech',
    location: 'Phnom Penh, Cambodia',
    schedule: 'Full-Time: 8:00 AM - 5:00 PM',
    paymentStatus: 'Payment Included',
    deadline: 'February 10, 2026',
    brandColor: Color(0xFFE91E63),
    logoKey: 'chip_mong',
    description: 'Develop Flutter mobile apps for Chip Mong retail ecosystem.',
    requirements: ['Flutter & Dart', 'Git'],
    stipend: '\$250 - \$400 / month',
  ),
  const InternshipOpportunity(
    id: 'cellcard-02',
    role: 'AI Specialist Intern',
    company: 'Cellcard',
    category: 'Tech',
    location: 'Phnom Penh, Cambodia',
    schedule: 'Full-Time: 8:30 AM - 5:30 PM',
    paymentStatus: 'Payment Included',
    deadline: 'February 15, 2026',
    brandColor: Color(0xFFFF9800),
    logoKey: 'cellcard',
    description: 'Build machine learning pipelines and customer analytics.',
    requirements: ['Python', 'SQL'],
    stipend: '\$300 - \$500 / month',
  ),
  const InternshipOpportunity(
    id: 'smart-03',
    role: 'Flutter Engineer Intern',
    company: 'Smart Axiata',
    category: 'Tech',
    location: 'Phnom Penh, Cambodia',
    schedule: 'Full-Time: 8:00 AM - 5:00 PM',
    paymentStatus: 'Payment Included',
    deadline: 'February 12, 2026',
    brandColor: Color(0xFF107C10),
    logoKey: 'smart',
    description: 'Build enterprise mobile applications for telecommunications.',
    requirements: ['Flutter', 'State Management'],
    stipend: '\$300 - \$450 / month',
  ),
  const InternshipOpportunity(
    id: 'hanuman-06',
    role: 'Data Analyst Intern',
    company: 'Hanuman',
    category: 'Tech',
    location: 'Phnom Penh, Cambodia',
    schedule: 'Full-Time: 8:00 AM - 5:00 PM',
    paymentStatus: 'Payment Included',
    deadline: 'February 20, 2026',
    brandColor: Color(0xFF8B6F47),
    logoKey: 'hanuman',
    description: 'Analyze distribution logistics and commercial beverage datasets.',
    requirements: ['Excel', 'PowerBI'],
    stipend: '\$250 - \$350 / month',
  ),
];
